import os
from dotenv import load_dotenv

load_dotenv()

BOT_PREFIX = "!"
DISCORD_TOKEN = "BOT_TOKEN"

APPLICATION_ID = 1375395675193475134

LAVALINK_HOST = "LAVALINK-HOST"
LAVALINK_PORT = 1234
LAVALINK_PASSWORD = "PASSWORD"
LAVALINK_NAME = "LAVA-NAME"
LAVALINK_SECURE = False

DEFAULT_VOLUME = 100
MAX_QUEUE_SIZE = 100
TIMEOUT_DURATION = 300